name: my_awesome_store
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  animate_do: ^4.2.0
  bloc_test: ^10.0.0
  connectivity_plus: ^6.0.3
  device_info_plus: ^12.1.0
  drift: ^2.28.2
  drift_flutter: ^0.2.7
  equatable: ^2.0.7
  intl: ^0.19.0
  excel: ^4.0.6
  fl_chart: ^1.1.1
  fluentui_system_icons: ^1.1.273
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^5.2.1
  fpdart: ^1.1.1
  get_it: ^8.2.0
  go_router: ^14.6.3
  google_fonts: ^6.3.2
  injectable: ^2.5.2
  json_annotation: ^4.9.0
  logger: ^2.6.1
  package_info_plus: ^8.1.5
  path_provider: ^2.1.5
  shared_preferences: ^2.3.5
  signature: ^6.3.0
  url_launcher: ^6.3.2
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.7.1
  drift_dev: ^2.28.3
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.3
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.8.1
  json_serializable: ^6.11.1
  very_good_analysis: ^10.0.0

# Configuración del ícono de la aplicación
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"
  
# Configuración de Splash Screen
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash_logo.png
  android_12:
    image: assets/images/splash_logo.png
    color: "#FFFFFF"
  ios: true
  android: true
  web: false

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - .env
    - .env.dev
    - .env.prod
